//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 05.12.2018 12:30:29
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Model
{
    public partial class Menu {

        public Menu()
        {
            OnCreated();
        }

        public virtual long ID
        {
            get;
            set;
        }

        public virtual long Tablo
        {
            get;
            set;
        }

        public virtual string Sıra
        {
            get;
            set;
        }

        public virtual Tablolar Tablolar
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
