//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilParametreleris
    {
        public long ID { get; set; }
        public string Kodu { get; set; }
        public long Dili { get; set; }
    
        public virtual Dillers Dillers { get; set; }
    }
}
